services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - polls_pg_data:/bitnami/postgresql
    networks:
      - iff

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - polls_redis_data:/bitnami/redis/data
    networks:
      - iff

volumes:
  polls_pg_data:
  polls_redis_data:

networks:
  iff:
    external: true
