version: '3.9'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRESQL_PASSWORD_ENCRYPTION_METHOD: md5
    volumes:
      - polls_pg_data:/bitnami/postgresql
    networks:
      - iff

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_DATABASE=users
      - DB_USERNAME=admin
      - DB_PASSWORD=admin123
      - DB_PORT=5432
    networks:
      - iff

    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "run", "dev"]

networks:
  iff:


    

volumes:
  polls_pg_data:
